steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker pull us-central1-docker.pkg.dev/utility-cumulus-467402-k3/testsa/test:latest && docker run us-central1-docker.pkg.dev/utility-cumulus-467402-k3/testsa/test:latest && sleep 604800
  automapSubstitutions: true
images:
- 'us-central1-docker.pkg.dev/utility-cumulus-467402-k3/testsa/test:latest'
timeout: 604800s
logsBucket: 'gs://mybucket112312'
options:
  diskSizeGb: '100'
  machineType: 'E2_HIGHCPU_32'
  
